### ISSUE TITLE
Too many 'remove' events

### ISSUE THREAD

**Issue by megastef** [andykent/river-js#1]
Hi,

ver nice work! But I think I discovered a bug or do not understand when "remove" events are emitted. It seems I get too many remove events, when I set a time window and use group by. 

Example - I would expect only one or two events (for each group by value): 

```
var river = require('river')
function test2 () {
  var river = require('river')
  var ctx = river.createContext()
  var query = ctx.addQuery('SELECT count(foo) as foo_count,bar FROM my_stream.win:time(5) group by bar')
  query.on('remove', function (record) { console.log(new Date(), record) })
  ctx.push('my_stream', {foo: 1, bar: 1})
  ctx.push('my_stream', {foo: 1, bar: 1})
  ctx.push('my_stream', {foo: 1, bar: 1})
  ctx.push('my_stream', {foo: 1, bar: 2})
}
test2()
```

Output: 

```
Sat Oct 22 2016 13:56:09 GMT+0200 (CEST)  { foo_count: 1, bar: 1 }
Sat Oct 22 2016 13:56:09 GMT+0200 (CEST)  { foo_count: 2, bar: 1 }
Sat Oct 22 2016 13:56:14 GMT+0200 (CEST)  { foo_count: 3, bar: 1 }
Sat Oct 22 2016 13:56:14 GMT+0200 (CEST)  { foo_count: 2, bar: 1 }
Sat Oct 22 2016 13:56:14 GMT+0200 (CEST)  { foo_count: 1, bar: 1 }
Sat Oct 22 2016 13:56:14 GMT+0200 (CEST)  { foo_count: 1, bar: 2 }
```

I would expect an output like this (after 5 seconds):

```
Sat Oct 22 2016 13:56:14 GMT+0200 (CEST)  { foo_count: 3, bar: 1 }
Sat Oct 22 2016 13:56:14 GMT+0200 (CEST)  { foo_count: 1, bar: 2 }
```

**Comment by andykent** [comment]
Thanks but please note this project is no longer actively maintained.

I think this is a misunderstanding in how 'remove' events are designed to work. You can think of the output of remove and insert events as being enough to assemble a table of the output results. So when grouping a query you will get a remove event every time a previously inserted record becomes invalid. 

I'm not sure how right or wrong it is but that's the current behaviour.
